# Generated by Django 4.2.3 on 2023-07-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid_id',
            new_name='uuid',
        ),
    ]
