# Generated by Django 4.2.3 on 2023-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_userqaprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='hel'),
            preserve_default=False,
        ),
    ]
