# Generated by Django 4.2.3 on 2023-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
